name : python_app_api

on:
  workflow_dispatch:

jobs:
  job1 :
    runs-on : ubuntu-latest
    steps:
      - uses : actions/checkout@v4
        with :
          repository : RaGuL-26/cicd-project-helping
          path : fastAPI


      - run : 
         python app/main.py

    

