name : cicd_lelevecho

on:
  workflow_dispatch:

jobs:
  java_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          javac javas/hello.java
          java -cp javas hello
