name : ifcicd

on:
  workflow_dispatch:

jobs:
  job1:
    env :
      abcd : 3
    runs-on : ubuntu-latest
    steps:
      - uses : actions/checkout@v4
      - run : echo "abcd"
      - if : ${{ env.abcd == 1 }}   
        run : echo "abbbdd"
      - if : ${{ env.abcd != 1 }}
        run : echo wrong
      - run : echo ${{ env.abcd}}
